name: Execução Diária do Robô

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
    - name: clonar repositório
      uses: actions/checkout@v3

    - name: Commit do relatório
      run: |
        git config user.name "Marlon Brito"
        git add dados/relatorio.csv
        git commit -m "Atualização diária" || echo "Nenhuma alteração a commitar"
        git push
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
